---
- name: Update apt cache
  apt: 
    update_cache: yes 
    cache_valid_time: 600

  when: ansible_os_family == 'Debian'
  changed_when: false


- name: Ensure NFS utilities are installed.
  apt:
    name:
      - nfs-common
      - nfs-kernel-server
    state: present
